### ISSUE TITLE
Safari (9.0) loading does not display in href tag

### ISSUE THREAD

**Issue by Neomoon** [hekigan/is-loading#15]
Ran across this issue during testing on a client application. It appears the anchor tags fail to display the loading screen correctly in Safari 9.0 (OsX 10.11). In our case we are using jQuery to handle the client side click event of some anchor tags and calling the isloading before we redirect. This has been validated to be working on: IE9 (Win), IE10(Win), FF 38.1.1(Win), Chrome 46 (Os X 10.11).

I was also able to replicate the behavior in your demo site (http://hekigan.github.io/is-loading/) by modifying the "Overlay" example: I changed the `<span>` button (line 170) to the following anchor tag
`<a href="http://hekigan.github.io/is-loading/" class="btn" onclick="$.isLoading({ text: &quot;Loading&quot; });">Test</a>`. Then I commented out the JS inside the `<script></script>` block (lines 176-195).  

So on all browsers but Safari the div overlay & animation is displayed before the re-direct occurs, but the Safari browser fails to display the overlay.

**Comment by brauliobo** [comment]
can confirm the same problem, although not even using `is-loading`, just a simple `onclick` callback isn't working for showing loading

**Comment by hekigan** [comment]
The problem was that Safari did not implement properly several things (document.createElement(), element.class, etc...).

In the new version (v2), is-loading is not a jQuery plugin anymore BUT, it plays well with it.
And I did double-check on Safari 8+, there should be no issue (hopefully).
I tried to keep things simple and flexible.
